// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://albqksdctimzpnizbmnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYnFrc2RjdGltenBuaXpibW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTAyMzMsImV4cCI6MjA2MDY4NjIzM30.Uko7yXTRVHQ4c9-D51X507mEV_0PBsGH5PBU0UUx1Ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);